#!/usr/bin/zsh

typeset -a args
args=(${@[*]})

function run_python {
if [[ -d $1 ]]; then
   $1/bin/python ${(@)args[@]}
fi
}

function run_pip {
if [[ -d $1 ]]; then
   $1/bin/pip ${(@)args[@]:1}
fi
}

typeset -a venv_names
venv_names=(venv .venv .python)

for name in $venv_names; do
   vpath=$PWD/$name
   if [[ $1 = '--pip' ]]; then
      run_pip $vpath
   else
      run_python $vpath
   fi
done

